export const titles = [
	{article: 'an', title: 'engineer'},
	{article: 'a', title: 'photographer'},
	{article: 'a', title: 'writer'},
	{article: 'an', title: 'author'},
	{article: 'an', title: 'artist'},
	{article: 'a', title: 'YouTuber'},
	{article: 'a', title: 'software engineer'},
	{article: 'a', title: 'fullstack engineer'},
	{article: 'a', title: 'Principal Software Engineer'},
	{article: 'a', title: 'Javascript apologist'},
	{article: 'a', title: 'Typescript aficionado'},
	{article: 'a', title: 'GraphQL enthusiast'},
	{article: 'an', title: 'ML engineer'},
	{article: 'an', title: 'app developer'},
	{article: 'an', title: 'athlete'},
	{article: 'a', title: 'beach volleyballer'},
	{article: 'a', title: 'powerlifter'},
	{article: 'a', title: 'gamer'},
	{article: 'a', title: 'mentor'},
	{article: 'a', title: 'teacher'},
	{article: 'a', title: 'student'},
	{article: 'a', title: 'friend'},
	{article: 'a', title: 'cook'},
	{article: 'an', title: 'illusionist'},
	{article: 'a', title: 'reviewer'},
	{article: 'a', title: 'partner'},
	{article: 'a', title: 'traveler'},
	{article: 'a', title: 'swashbuckler'},
	{article: 'an', title: 'explorer'},
	{article: 'a', title: 'nerd'},
	{article: 'a', title: 'geek'},
	{article: 'a', title: 'podcaster'},
	{article: 'a', title: 'streamer'},
	{article: 'a', title: 'cuber'},
	{article: 'a', title: 'dungeon master'},
	{article: 'an', title: 'island man'},
	{article: 'an', title: 'consultant'},
	{article: 'a', title: 'surfer'},
	{article: 'a', title: 'Svelte enjoyer'},
]
