export const roles = [
  'an engineer',
  'a photographer',
  'a writer',
  'an author',
  'an artist',
  'a YouTuber',
  'a software engineer',
  'a fullstack engineer',
  'a Javascript apologist',
  'a Typescript aficionado',
  'a GraphQL evangelist',
  'an ML engineer',
  'an app developer',
  'an athlete',
  'a beach volleyballer',
  'a powerlifter',
  'a gamer',
  'a mentor',
  'a teacher',
  'a student',
  'a friend',
  'a cook',
  'an illusionist',
  'a reviewer',
  'a partner',
  'a traveller',
  'a swashbuckler',
  'an explorer',
  'a nerd',
  'a geek',
  'a jock',
  'a dungeon master',
  'an island man',
]
